AWSTemplateFormatVersion: '2010-09-09-OC'

Parameters:
  targetIds:
    Type: CommaDelimitedList

Resources:
  Scp:
    Type: Community::Organizations::Policy
    Properties:
      Name: DenyLargeEC2Instances
      Description: Deny running EC2 instances larger than 4xlarge
      PolicyType: SERVICE_CONTROL_POLICY
      TargetIds: !Ref targetIds
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyLargerThan4XLarge
            Effect: Deny
            Action:
              - 'ec2:RunInstances'
            Resource: 'arn:aws:ec2:*:*:instance/*'
            Condition:
              ForAnyValue:StringNotLike:
                'ec2:InstanceType':
                  - '*.nano'
                  - '*.small'
                  - '*.micro'
                  - '*.medium'
                  - '*.large'
                  - '*.xlarge'
                  - '*.2xlarge'
                  - '*.4xlarge'
